version: '3.8'

services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PATH: "./cmd/api"
        FILE_NAME: "api"
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    command: "./api"
    restart: always
    depends_on:
      - postgres

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PATH: "./cmd/time_segment_worker"
        FILE_NAME: "time_segment_worker"
    command: "./time_segment_worker"
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data:
